### ISSUE TITLE
[Bug] Doesnt output container logs, only container states

### ISSUE THREAD

**Issue by Ki-er** [1RandomDev/docker-discord-logger#1]
Hi! 

This is a great idea and seems super useful, however I have tried to set it up and although I get the message saying `Started docker discord logger`, no logs are pushed to the channel.

I do get messages when the container is started

I may have misunderstood this project 😆 

Thanks!

**Comment by 1RandomDev** [comment]
> I may have misunderstood this project laughing

No you're right, the project is supposed to publish all the logs of a container to discord.

Are you sure you set the environment variable `CONTAINERS` to the correct names? You may also want to take a look at the logs of this container if it says anything like `Log listener for container container "..." exited`. That would indicate that the container you want to monitor was stopped or isn't running.

**Comment by Ki-er** [comment]
```
docker run -d --name=TwithcDropsLogger \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e CONTAINERS=TwitchDrops \
    -e WEBHOOK_URL=https://discord.com/api/webhooks/1014917716521525249/H0nGDVYKehjxwzywSE6m-YOcgyRkGmM1XkxTEwwKXQpauDUgS_hoU038bGIQQT2XXXX \
    ghcr.io/1randomdev/docker-discord-logger:latest
```
The xs on the webhook are to keep it private. 

Below is showing the container name and the logger setup
![image](https://user-images.githubusercontent.com/32241933/187951980-51b601b6-9868-47ef-8fc0-aac6a4916a83.png)

Output for discord
![image](https://user-images.githubusercontent.com/32241933/187952211-14158b4d-29ef-4cc3-80dc-24c5a2cef5ca.png)

> You may also want to take a look at the logs of this container if it says anything like Log listener for container container "..." exited. That would indicate that the container you want to monitor was stopped or isn't running.

This is not present in the container logs

**Comment by Ki-er** [comment]
Edit, I just tried a different container and it worked 😆 I will try other container and report back
